# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 309602c168e99740e2c2c862486368f92922d49c7f93c93830dd794887eca8cfe94c0375e0a220f5b3c104f6b3d24f8182c36a336e8735ae48c74658ccc07ae7

test:
  secret_key_base: ba9349eaa2719482c56200150c88d629b5a9cba821948f57a42b3cc967bb787b8d017b416afd602ae8f6b8f6fd37a024595dbdd3116246ac8e2620c6b00b7134

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
